### ISSUE TITLE
Unable to launch bash on ARMv6 architecture

### ISSUE THREAD

**Issue by alexellis** [resin-io-library/resin-rpi-raspbian#38]
```
docker run -ti resin/rpi-raspbian /bin/bash
docker run -ti resin/rpi-raspbian:jessie /bin/bash
```

Both of these fail.. this used to work.

**Comment by nghiant2710** [comment]
Hi @alexellis,
Since we had some changes in the entrypoint script, if you want to run it locally you need to override the entrypoint. So `docker run -ti --entrypoint=/bin/bash resin/rpi-raspbian:jessie` will work

**Comment by alexellis** [comment]
This is a breaking change :-/ I eventually worked it out but it lead to a lot of frustrated comments:

http://blog.alexellis.io/getting-started-with-docker-on-raspberry-pi/

**Comment by nghiant2710** [comment]
So sorry for that but this docker image supposed to run on resin device.
We will find a way to update the entry script to support your case

**Comment by alexellis** [comment]
It's testament to the quality of your image that it's being used as a base by most of the Docker/ARM community. Thanks for getting back - it would be great if you could look into this.

Thanks for putting this image out there.. I use it in my demos -> 

http://blog.alexellis.io/contain-yourself-in-london/

**Comment by nghiant2710** [comment]
@alexellis, in the meantime,  you can use this tag `jessie-20160831` it's a date fixed tag and doesn't have the breaking change. So you can have a stable base image for your work.

**Comment by nghiant2710** [comment]
Hey @alexellis, we have a PR to fix this issue https://github.com/resin-io-library/resin-rpi-raspbian/pull/39. Will let you know when it's merged

**Comment by petrosagg** [comment]
@alexellis pinging to let you know that this should be fixed now

**Comment by alexellis** [comment]
@petrosagg awesome, thanks for the ping. Let me check.. just pull `latest`?

**Comment by petrosagg** [comment]
@alexellis yes, any of the moving tags should work (`wheezy`, `jessie`, `latest`)
