### ISSUE TITLE
Image size showing as 3x previous size

### ISSUE THREAD

**Issue by alexellis** [resin-io-library/resin-rpi-raspbian#46]
I could be wrong but I can remember this image coming out at 30MBish, it's now 117.5 MB and that makes a huge difference for a Pi Zero.

Is this related to the backing FS on a Raspberry Pi? (overlay)

```
$ docker version
Client:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 03:23:36 2016
 OS/Arch:      linux/arm

Server:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 03:23:36 2016
 OS/Arch:      linux/arm

$ docker info
Containers: 7
 Running: 0
 Paused: 0
 Stopped: 7
Images: 20
Server Version: 1.12.5
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
```

**Comment by nghiant2710** [comment]
hey @alexellis, I'm not sure about overlayfs but the image size doesn't change. Please see on dockerhub here https://hub.docker.com/r/resin/rpi-raspbian/tags/

**Comment by nghiant2710** [comment]
as I recall, the image size is actually around 117.5 MB

**Comment by alexellis** [comment]
Thanks @nghiant2710
