### ISSUE TITLE
`fg` stderr output leaks to user logs

### ISSUE THREAD

**Issue by dfunckt** [resin-io-library/resin-rpi-raspbian#56]
When the user's app exits `fg` complains that the process terminated:

```
/usr/bin/entry.sh: line 93: fg: job has terminated
```

This output is captured by the Supervisor and sent over to the Dashboard as if it was output from the user application.

This is due to `fg`'s stderr not being redirected to `/dev/null` here: https://github.com/resin-io-library/resin-rpi-raspbian/blob/master/entry.sh#L93

That is without using systemd.

**Comment by nghiant2710** [comment]
fixed in https://github.com/resin-io-library/resin-rpi-raspbian/pull/63
