### ISSUE TITLE
I'm not able to start the image and run /bin/bash

### ISSUE THREAD

**Issue by gornialberto** [resin-io-library/resin-rpi-raspbian#60]
I tried to run the resin/rpi-raspbian image and executing the /bin/bash command but it seems not working.

This is the docker command i've used:

`docker run -it resin/rpi-raspbian /bin/bash`

**Comment by gornialberto** [comment]
Nevermind i found a way:

`docker run -it --entrypoint /bin/bash resin/rpi-raspbian`

Thanks to that link: https://gist.github.com/mitchwongho/11266726

Basically if the image specify an ENTRYPOINT specifying the command /bin/bash would not work.

**Comment by nghiant2710** [comment]
Fixed in https://github.com/resin-io-library/resin-rpi-raspbian/pull/63
