### ISSUE TITLE
Not able to start resin/rpi-raspbian container

### ISSUE THREAD

**Issue by suhailcheroor** [resin-io-library/resin-rpi-raspbian#67]
I am getting below error when i try to launch docker container.
Tried below commands, result is same.

**docker run -ti resin/rpi-raspbian
docker run -ti --entrypoint=/bin/bash resin/rpi-raspbian**

""""" panic: standard_init_linux.go:178: exec user process caused "exec format error" [recovered]
	panic: standard_init_linux.go:178: exec user process caused "exec format error"

goroutine 1 [running, locked to thread]:
panic(0x7e77c0, 0xc8200ff180)
	/usr/lib/go-1.6/src/runtime/panic.go:481 +0x3e6
github.com/opencontainers/runc/vendor/github.com/urfave/cli.HandleAction.func1(0xc8200ef300)
	/build/runc-Fx_CW1/runc-1.0.0~rc2/_build/src/github.com/opencontainers/runc/vendor/github.com/urfave/cli/app.go:478 +0x38e
panic(0x7e77c0, 0xc8200ff180)
	/usr/lib/go-1.6/src/runtime/panic.go:443 +0x4e9
github.com/opencontainers/runc/libcontainer.(*LinuxFactory).StartInitialization.func1(0xc8200eec10, 0xc82001a0c8, 0xc8200eed20)
	/build/runc-Fx_CW1/runc-1.0.0~rc2/_build/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:259 +0x136
github.com/opencontainers/runc/libcontainer.(*LinuxFactory).StartInitialization(0xc820051590, 0x7f4203397700, 0xc8200ff180)
	/build/runc-Fx_CW1/runc-1.0.0~rc2/_build/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:277 +0x5b1
main.glob.func8(0xc820072a00, 0x0, 0x0)
	/build/runc-Fx_CW1/runc-1.0.0~rc2/_build/src/github.com/opencontainers/runc/main_unix.go:26 +0x68
reflect.Value.call(0x74cd60, 0x8fddc8, 0x13, 0x8445f0, 0x4, 0xc8200ef280, 0x1, 0x1, 0x0, 0x0, ...)
	/usr/lib/go-1.6/src/reflect/value.go:435 +0x120d
reflect.Value.Call(0x74cd60, 0x8fddc8, 0x13, 0xc8200ef280, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/lib/go-1.6/src/reflect/value.go:303 +0xb1
github.com/opencontainers/runc/vendor/github.com/urfave/cli.HandleAction(0x74cd60, 0x8fddc8, 0xc820072a00, 0x0, 0x0)
	/build/runc-Fx_CW1/runc-1.0.0~rc2/_build/src/github.com/opencontainers/runc/vendor/github.com/urfave/cli/app.go:487 +0x2ee
github.com/opencontainers/runc/vendor/github.com/urfave/cli.Command.Run(0x8474a8, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x8dd200, 0x51, 0x0, ...)
	/build/runc-Fx_CW1/runc-1.0.0~rc2/_build/src/github.com/opencontainers/runc/vendor/github.com/urfave/cli/command.go:191 +0xfec
github.com/opencontainers/runc/vendor/github.com/urfave/cli.(*App).Run(0xc820001500, 0xc82000a100, 0x2, 0x2, 0x0, 0x0)
	/build/runc-Fx_CW1/runc-1.0.0~rc2/_build/src/github.com/opencontainers/runc/vendor/github.com/urfave/cli/app.go:240 +0xaa4
main.main()
	/build/runc-Fx_CW1/runc-1.0.0~rc2/_build/src/github.com/opencontainers/runc/main.go:132 +0xd98 """

**Comment by petrosagg** [comment]
Are you running those commands on a raspberrypi or on an X86 machine?

**Comment by suhailballippadi** [comment]
Docker is running on 64 bit Ubuntu EC2.

**Comment by petrosagg** [comment]
That's your problem. You can't run a vanilla ARM image (like this one) on non-ARM hardware. You'll have to setup QEMU emulation if you want to do this kind of thing
