### ISSUE TITLE
systemd is broken on stretch when using ENV INITSYSTEM on

### ISSUE THREAD

**Issue by bbinet** [resin-io-library/resin-rpi-raspbian#75]
I get the following error in balena logs:
```
Systemd init system enabled.
systemd 232 running in system mode. (+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN)
Detected virtualization docker.
Detected architecture arm.
Set hostname to <hlnew-mc-armv6hf>.
Cannot determine cgroup we are running in: No medium found
Failed to allocate manager object: No medium found
[!!!!!!] Failed to allocate manager object, freezing.
Freezing execution.
```
Searching resin.io forums points me to: https://forums.resin.io/t/the-failed-to-install-release-agent-bug-is-back/1810/5

It seems this bug has been fixed in debian base-images but not here in resin-rpi-raspbian, see the fix in esin-io-library/base-images repository:
- https://github.com/resin-io-library/base-images/pull/324
- https://github.com/resin-io-library/base-images/pull/342

I guess `resin/rpi-raspbian:stretch` should not have a `VOLUME [/sys/fs/cgroup]` layer (as `resin/armv7hf-debian:stretch` does not have this `VOLUME [/sys/fs/cgroup]` layer).

**Comment by nghiant2710** [comment]
@bbinet, thanks a lot for your report. Fixed in https://github.com/resin-io-library/resin-rpi-raspbian/pull/76. The new images will be available soon.

**Comment by esetnik** [comment]
I am seeing this same issue in `resin/beaglebone-black-node-node:slim` based images.
